### ISSUE TITLE
running app in background/ accessing console during shiny session

### ISSUE THREAD

**Issue by tnaake** [ComputationalProteomicsUnit/pRolocGUI#5]
I asked on stack overflow if it's possible to access the console while running a shiny application. There should be a possibility by using a daemonized server. This can/should be implemented in future:

http://stackoverflow.com/questions/24020636/access-use-r-console-when-running-a-shiny-app

**Comment by Kohze** [comment]
There we could simply run instead of the direct runApp() call a  `system("...")` with the codeline below, then it wouldnt block the R kernel anymore.   

**Running in a Separate Process**
If you don’t want to block access to the console while running your Shiny application you can also run it in a separate process. You can do this by opening a terminal or console window and executing the following, where ~/shinyapp should be replaced with the path to your application:

`R -e "shiny::runApp('~/shinyapp')"`

https://shiny.rstudio.com/articles/running.html

**Comment by Kohze** [comment]
A proof of concept of non-blocking shiny applications. The only thing we need to test then is whether we can pass variables/objects to the shiny session as required for pRolocGUI. Otherwise we the workaround of the not passing variables would be to create a temp rData file which is taken up by the shiny session. 

```
path = paste0("R -e \"shiny::runApp(\'", getwd(), "\', launch.browser = TRUE)\"")
system(path, wait = FALSE) 
```

![shiny_system](https://cloud.githubusercontent.com/assets/16598797/24428067/757075fe-140d-11e7-9b76-3b6c574f34ff.gif)

**Comment by LNsanpython** [comment]
This doesn't work for me. Is there an alternative?

**Comment by lmsimp** [comment]
Hello thanks for your comment, unfortunately it’s not currently possible to access the R console whilst running the pRoloc app.
