### ISSUE TITLE
old compare app takes "list" not "MSnSetList"

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#54]
Should I change this now? 

Doc says `object` should be an `MSnSetList` but `MSnSetList` does not work.

**Comment by lgatto** [comment]
It's `object` in the code, so must also be `object` in the doc.

**Comment by lmsimp** [comment]
Yes, but we state in the do that `object` is of class `MSnSet` or `MSnSetList` when in fact at the moment it's on `MSnSet` or `list`. It doesn't really matter as we are about to replace the compare app with a new one and this will require an `MSnSetList`, I was just thinking of existing users.

**Comment by lgatto** [comment]
Then, in the doc we should say `MSnSet` or `list` (or `MSnSetList` if also relevant for now). 

The arguments could also be named differently, so that the doc would differentiate the cases. Maybe we should use `x` (or `object` or `mset`) whenever it's an `MSnbase` and  `y` (or `msetList`) whenever it's an `MSnSetList`, so that we keep the two cases distinct in the man file.

**Comment by lmsimp** [comment]
Closing, let's discuss tomorrow. Will just change doc to `list` for now as I don't want to play around with old code. It will be `MSnSetList` in the new app.

**Comment by lgatto** [comment]
I don't like using the same name as the object class itself, to be honest.
