### ISSUE TITLE
Avoid recalculating the dimension reduction at every reaction

### ISSUE THREAD

**Issue by lgatto** [ComputationalProteomicsUnit/pRolocGUI#90]
Whenever a user interacts with the plot, `plot2D` is called with the `MSnSet`, and PCA is re-calculated. This is a problem with one sets `method = "t-SNE"`, because (1) t-SNE takes time and (2) we get a new plot. 

We need to store the output of `plot2D` once, then pass it to all subsequent `plot2D` class.

**Comment by lgatto** [comment]
This is fixed in 7a9509f9b5284588a1833b4d88f6dfcf81153200. 

@kbarylyuk - it is not possible to use t-SNE in `pRolocVis`:

```r
library("pRolocdata")
data(dunkley2006)
library("pRolocGUI")
pRolocVis(dunkley2006, method = "t-SNE", methargs = list(perplexity = 50))
```

**Comment by kbarylyuk** [comment]
Would be nice to have an option to use precalculated coordinates (of a user's favorite projection, which otherwise might still take a long time to calculate) explicitly as an input, similar to how it is implemented in `plot2D`:

`pRolocVis(object = MyCoordinates, method = "none", methargs = list(MyMSnSet))`

**Comment by lgatto** [comment]
Yes, indeed. While it should be relatively easy to do, programming wise, I won't be able to do it at the moment. I'll do this the next time I work on `pRolocGUI`.
